{application,patience_game,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{patience_game_app,[]}},
              {env,[]},
              {modules,[patience_game_app,patience_game_sup,patience_manager,
                        pile_util]}]}.
